### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Config
  commentId: N:Vintagestory.API.Config
  id: Vintagestory.API.Config
  children:
  - Vintagestory.API.Config.Dimensions
  - Vintagestory.API.Config.EnumGameBranch
  - Vintagestory.API.Config.EnumReleaseType
  - Vintagestory.API.Config.FoodSpoilageCalcDelegate
  - Vintagestory.API.Config.GamePaths
  - Vintagestory.API.Config.GameVersion
  - Vintagestory.API.Config.GlobalConstants
  - Vintagestory.API.Config.ITranslationService
  - Vintagestory.API.Config.Lang
  - Vintagestory.API.Config.OS
  - Vintagestory.API.Config.RuntimeEnv
  - Vintagestory.API.Config.TranslationService
  langs:
  - csharp
  - vb
  name: Vintagestory.API.Config
  nameWithType: Vintagestory.API.Config
  fullName: Vintagestory.API.Config
  type: Namespace
  assemblies:
  - VintagestoryAPI
references:
- uid: Vintagestory.API.Config.Dimensions
  commentId: T:Vintagestory.API.Config.Dimensions
  href: Vintagestory.API.Config.Dimensions.html
  name: Dimensions
  nameWithType: Dimensions
  fullName: Vintagestory.API.Config.Dimensions
- uid: Vintagestory.API.Config.GamePaths
  commentId: T:Vintagestory.API.Config.GamePaths
  href: Vintagestory.API.Config.GamePaths.html
  name: GamePaths
  nameWithType: GamePaths
  fullName: Vintagestory.API.Config.GamePaths
- uid: Vintagestory.API.Config.EnumGameBranch
  commentId: T:Vintagestory.API.Config.EnumGameBranch
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.EnumGameBranch.html
  name: EnumGameBranch
  nameWithType: EnumGameBranch
  fullName: Vintagestory.API.Config.EnumGameBranch
- uid: Vintagestory.API.Config.EnumReleaseType
  commentId: T:Vintagestory.API.Config.EnumReleaseType
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.EnumReleaseType.html
  name: EnumReleaseType
  nameWithType: EnumReleaseType
  fullName: Vintagestory.API.Config.EnumReleaseType
- uid: Vintagestory.API.Config.GameVersion
  commentId: T:Vintagestory.API.Config.GameVersion
  href: Vintagestory.API.Config.GameVersion.html
  name: GameVersion
  nameWithType: GameVersion
  fullName: Vintagestory.API.Config.GameVersion
- uid: Vintagestory.API.Config.FoodSpoilageCalcDelegate
  commentId: T:Vintagestory.API.Config.FoodSpoilageCalcDelegate
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.FoodSpoilageCalcDelegate.html
  name: FoodSpoilageCalcDelegate
  nameWithType: FoodSpoilageCalcDelegate
  fullName: Vintagestory.API.Config.FoodSpoilageCalcDelegate
- uid: Vintagestory.API.Config.GlobalConstants
  commentId: T:Vintagestory.API.Config.GlobalConstants
  href: Vintagestory.API.Config.GlobalConstants.html
  name: GlobalConstants
  nameWithType: GlobalConstants
  fullName: Vintagestory.API.Config.GlobalConstants
- uid: Vintagestory.API.Config.OS
  commentId: T:Vintagestory.API.Config.OS
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.OS.html
  name: OS
  nameWithType: OS
  fullName: Vintagestory.API.Config.OS
- uid: Vintagestory.API.Config.RuntimeEnv
  commentId: T:Vintagestory.API.Config.RuntimeEnv
  href: Vintagestory.API.Config.RuntimeEnv.html
  name: RuntimeEnv
  nameWithType: RuntimeEnv
  fullName: Vintagestory.API.Config.RuntimeEnv
- uid: Vintagestory.API.Config.ITranslationService
  commentId: T:Vintagestory.API.Config.ITranslationService
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.ITranslationService.html
  name: ITranslationService
  nameWithType: ITranslationService
  fullName: Vintagestory.API.Config.ITranslationService
- uid: Vintagestory.API.Config.Lang
  commentId: T:Vintagestory.API.Config.Lang
  href: Vintagestory.API.Config.Lang.html
  name: Lang
  nameWithType: Lang
  fullName: Vintagestory.API.Config.Lang
- uid: Vintagestory.API.Config.TranslationService
  commentId: T:Vintagestory.API.Config.TranslationService
  href: Vintagestory.API.Config.TranslationService.html
  name: TranslationService
  nameWithType: TranslationService
  fullName: Vintagestory.API.Config.TranslationService
- uid: Vintagestory.API.Config
  commentId: N:Vintagestory.API.Config
  href: Vintagestory.html
  name: Vintagestory.API.Config
  nameWithType: Vintagestory.API.Config
  fullName: Vintagestory.API.Config
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
